name: CI

on: [push, fork, pull_request, workflow_dispatch, workflow_call]

jobs:

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: crate-ci/typos@master

  py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          pip install uv
          uv tool run pdm export --pyproject | uv pip install --system -r -
          yarn global add pyright
      - name: Ruff
        run: |
          ruff format --check --diff
          ruff check --diff
      - name: Pyright
        run: pyright --stats

  js:
    strategy:
      matrix:
        os: [ubuntu, macos]
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v5

      - name: Pull changes
        run: git pull || true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # stackblitz supports pnpm v8

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install dependencies
        working-directory: app
        run: pnpm install

      - name: Lint
        working-directory: app
        run: pnpm lint

      - name: Check
        working-directory: app
        run: pnpm check

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu'
        with:
          path: app/pnpm-lock.yaml
          name: lockfile

  lock:
    if: github.event_name != 'pull_request' 
    needs: [typos, py, js]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          path: app
          name: lockfile
      - name: Commit changes
        run: |
          git pull || true
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          sed -i '/pnpm-lock.yaml/d' .gitignore
          git add app/pnpm-lock.yaml .gitignore
          rm -rf .github
          locked_branch_name=$(git branch --show-current)-locked
          git checkout -b $locked_branch_name
          git commit -m 'add `pnpm-lock.yaml`'
          git push --set-upstream origin $locked_branch_name -f

  deploy:
    runs-on: ubuntu-latest
    if:
      github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Build static site
        working-directory: app
        run: pnpm install --prod && pnpm build
      - name: Upload pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: app/build
      - name: Deploy
        uses: actions/deploy-pages@v4
        id: deployment
